@startuml
class org.optaplanner.core.impl.localsearch.decider.forager.privacypreserving.StepStatistic {
- Score stepScore
- Score thresholdScore
- Integer bucketSize
- Integer stepIndex
- boolean foundNewSolution
+ Score getStepScore()
+ void setStepScore(Score)
+ Score getThresholdScore()
+ void setThresholdScore(Score)
+ Integer getBucketSize()
+ void setBucketSize(Integer)
+ Integer getStepIndex()
+ void setStepIndex(Integer)
+ boolean isFoundNewSolution()
+ void setFoundNewSolution(boolean)
}
@enduml